pasqal-io/Pulser

pulser/simulation.py
tutorials/Preparing state with antiferromagnetic order in the Ising model.ipynb

I couldn't push the last changes following Loic's review before the merge.

Add final changes

---

CONTRIBUTING.md
README.md

We were missing this part of an open-source repo, it's important to show outsiders how they should proceed and to lay out some sort of organised system. 
I kinda made some of these rules up based on what seemed reasonable to me, so I would appreciate your review and feedback.

Adding Contribution guidelines

---

pulser/simulation.py
pulser/tests/test_simulation.py

Creates a property for the Hamiltonian object, so that it doesn't get mixed up with the internal attribute which is used during the initialization.
Closes #108

Getter For Hamiltonian 

---

.github/workflows/ci.yml
.mypy.ini
CONTRIBUTING.md
pulser/channels.py
pulser/devices/_device_datacls.py
pulser/json/utils.py
pulser/register.py
pulser/waveforms.py
requirements.txt
setup.py

- Add mypy config file
- Adds mypy to CI workflow
- Cleans up errors in mypy checks

Setting up mypy

---

.gitattributes

As mentioned in #189, this PR updates linguist's calculation to better reflect the source language of the project.

Updates linguist's calculation for `Pulser`

---

.flake8
pulser/_seq_drawer.py
pulser/channels.py
pulser/json/coders.py
pulser/json/utils.py
pulser/parametrized/decorators.py
pulser/parametrized/paramabc.py
pulser/parametrized/paramobj.py
pulser/parametrized/variable.py
pulser/pulse.py
pulser/register.py
pulser/sequence.py
pulser/simulation/simconfig.py
pulser/simulation/simresults.py
pulser/simulation/simulation.py
pulser/waveforms.py
requirements.txt

Incorporating flake8-docstring checks into CI

---

pulser/sequence.py
pulser/simulation/simconfig.py
pulser/tests/test_waveforms.py
pulser/waveforms.py
requirements.txt
setup.py

Adds `__getitem__` to waveform.
Adds corresponding tests.
First PR : ConstantWaveform only, for review.

Add __getitem__ to waveforms (#203)

---

pulser/_seq_drawer.py
pulser/sequence.py
pulser/simulation/simulation.py
pulser/tests/test_paramseq.py
pulser/tests/test_sequence.py

This one has been a long time coming.
Fixes #112 .

Add `Sequence.get_duration()`

---

pulser/_version.py

Bug fixes:
- Fixes incompatibility between initial state setting and state preparation errors
Additions:
- Tutorial on the Quantum Estimation Kernel

Release v0.3.1

---

pulser/_version.py

- Fixed global-local overwriting bug when noise is involved and added tests

Release v0.3.2

---

pulser/simulation/simulation.py

Minor changes so that XY mode can be simulated on 3D Registers.

Generalizing XY mode simulation for 3D

---

tutorials/applications/Quantum Evolution Kernel.ipynb

fixed harmless typo in create_random_graphs

---

pulser/_seq_drawer.py
pulser/register.py
pulser/sequence.py
pulser/tests/test_json.py
pulser/tests/test_register.py

Add Register3D _to_dict method and UTs

---

pulser/devices/_device_datacls.py
requirements.txt

Fixes the mypy version to 0.921 to avoid surprises from package updates.

Fixing mypy to 0.921

---

pulser/_seq_drawer.py
pulser/devices/_device_datacls.py
pulser/json/utils.py
pulser/register.py
pulser/simulation/simresults.py
pulser/simulation/simulation.py
pulser/tests/test_parametrized.py
pulser/tests/test_simulation.py

Changes from black 22.1.0

---

setup.py

Enable to use typed hints with mypy when using the Pulser library

Ship typed hints to the library's users

---

.github/workflows/ci.yml
CONTRIBUTING.md

Following #320, this PR adds CI checks for `isort` and `black[jupyter]` .

New CI checks

---

pulser/parametrized/paramobj.py
pulser/parametrized/variable.py
pulser/sequence.py
pulser/tests/test_json.py
pulser/tests/test_parametrized.py
pulser/tests/test_paramseq.py

PR corresponding to the issue [https://github.com/pasqal-io/Pulser/issues/325](https://github.com/pasqal-io/Pulser/issues/325)
I still have to fix a problem when trying to rename the classes, falling on a `TypeError: 'ABCMeta' object is not subscriptable` error.

Generalize variable

---

.mypy_script
.pre-commit-config.yaml
CONTRIBUTING.md
requirements.txt

- add pre-commit hooks
- update contributing guidelines with pre-commit usage

Adding CI checks with git hooks and pre-commit

---

docs/source/apidoc/creation.rst
pulser/register/register_layout.py

Updates the documentation of the `pulser.register` module.

Updates to the documentation

---

pulser/sequence.py

An initial version of an abstract serialization of the Pulser sequences. 
As of now, while it is not general, it supports https://github.com/pasqal-io/Pulser/blob/develop/tutorials/advanced_features/Serialization.ipynb.
It might serve as a starting point and comparison for more robust export approaches.

Initial version of abstract sequence format

---

pulser/tests/test_sequence.py

Abstract represenation test

---

pulser/simulation/noises.py

Removing duplicate NoiseModel definition

---

docs/requirements.txt
docs/source/_static/css/max_width.css
docs/source/conf.py

This is nothing definitive, but I wanted to give RTD one last shot and see how it would look if we customize it to support larger displays. 
I'm opening this PR essentially to start a build on the RTD server.

Customizing RTD theme to support larger screens

---

pulser-core/pulser/register/_reg_drawer.py
pulser-core/pulser/register/register_layout.py
tests/test_parametrized.py

The latest version of `numpy` raised a couple of `mypy` issues in the CI checks, these changes fix them.

Fixing mypy issues from numpy v1.23

---

.coveragerc
.github/workflows/pulser-setup/action.yml
.gitignore
.mypy.ini
.readthedocs.yml
Makefile
README.md
docs/source/installation.rst
packages.txt
pulser-pasqal/LICENSE
pulser-pasqal/MANIFEST.in
pulser-pasqal/README.md
pulser-pasqal/pulser_pasqal/__init__.py
pulser-pasqal/pulser_pasqal/_version.py
pulser-pasqal/requirements.txt
pulser-pasqal/rtd_requirements.txt
pulser-pasqal/setup.py
pyproject.toml
setup.py
tests/test_pasqal.py

Create the `pulser-pasqal` extension package

---

pulser-simulation/pulser_simulation/simulation.py

Fix type annotation in run() method of Simulation() class.

---

docs/requirements.txt
docs/source/index.rst
docs/source/tutorials/reg_layouts.nblink
pulser-core/pulser/json/abstract_repr/deserializer.py
pulser-core/pulser/register/register_layout.py
tests/test_abstract_repr.py
tutorials/advanced_features/Register Layouts.ipynb

Register Layout updates

---

dev_requirements.txt
pulser-core/pulser/json/abstract_repr/deserializer.py
pulser-core/pulser/register/_reg_drawer.py
pulser-core/pulser/waveforms.py
pulser-simulation/pulser_simulation/simresults.py
tests/test_abstract_repr.py
tests/test_channels.py
tests/test_sequence.py
tests/test_simulation.py
tests/test_waveforms.py
tutorials/applications/Control-Z Gate Sequence.ipynb
tutorials/quantum_simulation/Building 1D Rydberg Crystals.ipynb

Upgrading black to v23.1

---

pulser-core/pulser/sequence/_seq_drawer.py
tests/test_register_layout.py
tests/test_sequence.py

Display the EOM start buffer, EOM block and EOM end buffer when drawing a sequence.
Closes #463

 Highlight EOM buffers in Sequence drawings

---

pulser-core/pulser/register/special_layouts.py
tests/test_devices.py
tests/test_register_layout.py
tutorials/advanced_features/Register Layouts.ipynb

Fixes #485 
Allow non-integer spacing in special register layouts

Allow non-integer spacing in special register layouts

---

.mypy.ini
dev_requirements.txt
pulser-core/pulser/channels/base_channel.py
pulser-core/pulser/devices/_device_datacls.py
pulser-core/pulser/register/register.py
pulser-core/pulser/register/register3d.py
pulser-core/pulser/register/register_layout.py
pulser-core/pulser/sequence/sequence.py
pulser-core/pulser/waveforms.py
pulser-simulation/pulser_simulation/simulation.py
tests/test_abstract_repr.py

Move to mypy 1.2

---

pulser-pasqal/pulser_pasqal/__init__.py
pulser-pasqal/pulser_pasqal/pasqal_cloud.py
pulser-pasqal/requirements.txt
tests/test_pasqal.py

Switching from `pasqal-sdk` to `pasqal-cloud`

---

pulser-core/pulser/json/abstract_repr/deserializer.py
tests/test_abstract_repr.py

Fixes the deserialization from the abstract representation of parametrized pulses created through `Pulse` classmethods (i.e. `Pulse.ConstantAmplitude` and `Pulse.ConstantDetuning`).

FIX: Deserialization of parametrized pulses with constant parameters

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/test.yml
README.md
docs/source/installation.rst
pulser-core/pulser/channels/base_channel.py
pulser-core/pulser/devices/_device_datacls.py
pulser-core/pulser/parametrized/paramobj.py
pulser-core/pulser/register/register_layout.py
pulser-core/pulser/sequence/sequence.py
pulser-core/pulser/waveforms.py
pulser-core/requirements.txt
pulser-core/setup.py
pulser-pasqal/setup.py
pulser-simulation/pulser_simulation/simconfig.py
pulser-simulation/requirements.txt
pulser-simulation/setup.py
setup.py

Drop support for Python 3.7

---

pulser-core/pulser/devices/interaction_coefficients/__init__.py
pulser-core/requirements.txt

Fixes #547 
Also takes care of a silent warning that was showing up in the tests.

Pin jsonschema to fix broken CI tests

---

docs/source/apidoc/core.rst
pulser-core/pulser/devices/__init__.py
pulser-core/pulser/devices/_device_datacls.py
pulser-core/pulser/devices/_devices.py
tests/test_abstract_repr.py
tutorials/advanced_features/Output Modulation and EOM Mode.ipynb

Defines a realistic device for analog quantum computation.

Defining AnalogDevice

---

pulser-core/pulser/json/coders.py
pulser-core/pulser/sequence/sequence.py
tests/test_json.py

The latest version of `flake8` introduced  an extra style guideline that we were not respecting.

Comply with latest style guidelines

---

pulser-core/pulser/json/abstract_repr/serializer.py
pulser-core/pulser/sequence/sequence.py
tests/test_sequence.py

Updates to the target methods

---

pulser-core/pulser/register/weight_maps.py
tests/test_dmm.py

FIX: Coordinate matching in `WeightMap.get_qubit_weight_map()`

---

tests/test_backend.py
tests/test_sequence.py
tests/test_simulation.py

It seems that the new pytest 8.0.0 uncovered some mistakes in our tests... These are the fixes.

[FIX] Restore compatibility with pytest 8.0.0

---

pulser-core/pulser/channels/dmm.py
tests/test_abstract_repr.py
tests/test_backend.py
tests/test_dmm.py
tests/test_sequence.py

It has been decided to solve #626 in v0.18.

Modify deprecation of total_bottom_detuning to v0.18

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/pulser-setup/action.yml
.github/workflows/test.yml
.github/workflows/version.yml

I noticed some of the actions we are using in our workflow are now deprecated (something to do with Node JS 16 reaching its EOL), so here are the updates.

Update Github Actions

---

pulser-core/pulser/json/abstract_repr/serializer.py
pulser-core/pulser/sequence/sequence.py
tests/test_abstract_repr.py
tests/test_sequence_sampler.py

Optionally skip JSON schema validation after serialization

---

pulser-core/pulser/json/abstract_repr/deserializer.py
pulser-core/pulser/json/abstract_repr/schemas/device-schema.json
pulser-core/pulser/json/abstract_repr/schemas/layout-schema.json
pulser-core/pulser/json/abstract_repr/schemas/register-schema.json
pulser-core/pulser/json/abstract_repr/schemas/sequence-schema.json
pulser-core/pulser/json/abstract_repr/serializer.py
pulser-core/pulser/register/base_register.py
pulser-core/pulser/register/register.py
pulser-core/pulser/register/register3d.py
tests/test_abstract_repr.py

Support for 3D registers and layouts in the abstract representation

---

.github/workflows/ci.yml
pulser-core/pulser/sequence/_seq_drawer.py

Hide Rabi frequency when drawing DMM channels

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Support Python 3.13

---

pulser-core/pulser/backend/config.py
pulser-core/pulser/backend/default_observables.py
pulser-core/pulser/json/abstract_repr/backend.py
pulser-core/pulser/json/abstract_repr/deserializer.py
tests/test_backend_abstract_repr.py

Add EmulationConfig deserializer

---

docs/source/apidoc/simulation.rst
pulser-core/pulser/backends.py
pulser-simulation/pulser_simulation/__init__.py
pulser-simulation/pulser_simulation/qutip_backend.py
pulser-simulation/pulser_simulation/qutip_config.py
pulser-simulation/pulser_simulation/simulation.py
tests/pulser_simulation/test_qutip_backend.py
tests/pulser_simulation/test_qutip_backend_v2.py
tests/pulser_simulation/test_qutip_config.py
tests/pulser_simulation/test_simulation.py

Create QutipConfig and QutipBackendV2 (Henrique)
Add handling of non-lindbladian noise

Add QutipBackendV2: using Qutip with new API

---

.github/scripts/package.sh
.github/workflows/publish.yml

Replace wheel with build for packaging

---

pulser-core/pulser/backend/operator.py
pulser-core/pulser/backend/state.py
pulser-simulation/pulser_simulation/qutip_op.py
pulser-simulation/pulser_simulation/qutip_state.py
tests/pulser_simulation/test_qutip_state_op.py
tests/test_operator.py
tests/test_state.py

We have a similar thing twice in emulators repo and I would like to get rid of it

Factorize eigenstates and FullOp validation

---

pulser-core/pulser/json/abstract_repr/deserializer.py
pulser-core/pulser/json/abstract_repr/schemas/sequence-schema.json
pulser-core/pulser/json/abstract_repr/serializer.py
tests/test_abstract_repr.py

Needed to consider #873 actually closed.

Support de/serialization of Sequence.truncate()

---

pulser-core/pulser/math/abstract_array.py

Stop detaching when converting AbstractArray to float
