pasqal-io/Pulser

pulser/register.py, pulser/tests/test_register.py
The `Register.from_coordinates` class method did two things wrong: Changed the input in-place and raised an error when the type of the `coords` array was not a float. This tiny PR fixes both these mistakes and also tightens up the related test.
=> Fixing a bug in Register.from_coordinates

pulser/pulse.py, pulser/tests/test_pulse.py
Following our discussion, this PR serves to eliminate the `_chirps` method from the `Pulse` class, as it doesn't have any use inside Pulser. 
Closes #75 .
=> Removing _chirps from Pulse

README.md, docs/source/installation.rst, setup.py
These changes serve to prepare `master` for the release v0.1.0. They are simple modifications to: `setup.py`, the `README` and some docs pages.
=> v0.1.0 release

README.md, docs/source/conf.py, docs/source/index.rst, pulser/_version.py, setup.py
I noticed that the docs version was not up-to-date with the version of `pulser`, and then I remember that there's a version parameter in `conf.py` that I forgot about. 
This is not a big deal and I don't think it warrants sending out a new release, but I thought it would be good to have the version information in a single place and then get if from there, wherever it is needed. I'm also updating it with the `dev` suffix to distinguish if from the released package. This way, for the next release, we just bump it to the next version (say, `v0.1.1`), upload the package to PyPI and then bump it again (to `v0.1.1.dev`) to keep working on it here. 
Also, calling `pulser.__version__` now returns the version, which is expected behaviour that we did not have.
I also took the chance to have two …
=> Centralising version tracking

pulser/simulation.py
I changed the way the local operator builder works by. using list comprehension. This runs faster than using a loop after first creating a list of identities. No further changes in notebooks, although one can run the nb again and see the speed improves slightly (~5-10%)
=> Create local operators by list comprehension.

pulser/simresults.py
The latest version of `qutip` (4.5.3) does not allow a direct call of `np.abs` on a `QObj`, so this is a fix where the data is explicitly retrieved and turned into a `np.ndarray` beforehand.
@sebgrijalva : Before we merge this, can you think of anywhere else where something like this might be happening?
=> Fixing compatibility issue with latest version of QuTiP

pulser/devices/_pasqal_device.py, pulser/register.py, pulser/tests/test_devices.py, pulser/tests/test_register.py
There we no checks on the atom coordinates given to a Register upon initialisation and although these were verified by `PasqalDevice.validate_register()`, it still gave rise to bugs when calling the register methods e.g. when drawing a register with 3D coordinates or even 2D coordinates of type `int`.
These changes look out for invalid inputs, standardise how the information is stored and make the whole class less prone to spurious errors.
=> Increasing robustness of Register initialisation

pulser/tests/test_waveforms.py, pulser/waveforms.py
Implements negation, scalar multiplication and scalar division of waveforms. 
All operations change the waveform's samples, not the duration.
Closes #98 .
=> Implement multiplication by scalar and negation on waveforms

pulser/register.py, pulser/tests/test_register.py
As discussed, the graph is now drawn by default when given the blockade radius.
@sebgrijalva : I didn't remove the `draw_` from the args because, without them, it seemed to me that it would imply that `blockade_radius` was actually `draw_blockade_radius`. Do you see what I mean?
=> Draw the graph by default, when given a blockade radius

pulser/simulation.py, pulser/tests/test_simulation.py
Fixes a bug in case `Register` contains only one atom. Includes testing for the creation of the `SimulationResults` object.
=> Single atom hotfix

.coveragerc, .github/workflows/ci.yml, CONTRIBUTING.md, pulser/_seq_drawer.py, pulser/tests/test_sequence.py
Since we'll start receiving outside contributions, I figured it's a good idea to ask for 100% unit test coverage. This PR reaches 100% coverage on the existing code and enforces 100% coverage on the CI tests.
There is still the option to use the `# pragma: no cover` comment on lines that can't be tested, although it should only be used under special circumstances.
@lhenriet @sebgrijalva There is not much to review, I'm requesting a review from your side as more of an acknowledgement of these changes.
=> Reaching and enforcing 100% coverage

pulser/tests/test_waveforms.py, pulser/waveforms.py
I stumbled upon the fact that `Waveform` or `Pulse`, created through a `classmethod` that processes the input arguments somehow, will most likely not support `Parametrized` arguments unless specifically stated.
So far, this is the only case where that happens, but should other cases appear, perhaps we should make a standard decorator to deal with this systematically.
=> Supporting parametrized arguments in BlackmanWaveform.from_max_val

docs/source/introduction_rydberg_blockade.ipynb, docs/source/pulser.rst, pulser/__init__.py, pulser/devices/_device_datacls.py, pulser/devices/_devices.py, pulser/devices/_mock_device.py, pulser/devices/_pasqal_device.py, pulser/sequence.py, pulser/tests/test_sequence.py, tutorials/applications/Building 1D Rydberg Crystals.ipynb, tutorials/applications/Control-Z Gate Sequence.ipynb, tutorials/applications/Using QAOA to solve a MIS problem.ipynb
- `PasqalDevice` was renamed `Device`
- Other mentions of Pasqal were omitted
- A `Sequence` no longer enforces the device to be imported from `pasqal.devices`, it just demands it be a `Device` instance. A warning is still issued in cases where the user makes their own device.
=> Removing Pasqal mentions + Relaxing restrictions on allowed devices for Sequences

pulser/channels.py, pulser/devices/_mock_device.py, pulser/sequence.py, pulser/simulation.py, pulser/tests/test_devices.py, pulser/tests/test_sequence.py, pulser/tests/test_simulation.py
- The `Microwave` channel is added as new type of `Channel`
- The `'xy'` basis is introduced (**this name is up for debate**)
- `Sequence` identifies whether it is working with `Microwave` channels or the other types. It decides based on the first added channel and forbids mixing channels that have different modes of operation.
- For now, raises errors in `Simulation` to clarify that a `Sequence` working in the XY Hamiltonian cannot be simulated.
Closes #72 .
=> Adding the Microwave channel and operation mode

docs/source/introduction_rydberg_blockade.ipynb, tutorials/applications/Preparing state with antiferromagnetic order in the Ising model.ipynb
Uses `square(N_side, ...)` instead of `rectangle(N_side, N_side, ...)`
Corrects typo: `neutral` instead of `netural`
=> Small changes in the documentation (rectangle vs. square) and typo on "neutral"

pulser/_seq_drawer.py, pulser/channels.py, pulser/devices/_device_datacls.py, pulser/pulse.py, pulser/sequence.py, pulser/waveforms.py
Hello,
This PR tries to make a small change by making strings consistent by replacing the `.format` syntax with f-strings.
Thanks!
=> Change instances of `.format` to f-strings [unitaryHACK]

pulser/register.py, pulser/tests/test_register.py
I thought the `max_connectivity()` was nice enough that expanding its use for less than 7 atoms would be useful. This PR includes these cases, occupying one by one the sites of an underlying hexagon coordinate list.
=> Expand `Register.max_connectivity()` for few atoms.

pulser/channels.py
I had to use `# type: ignore` on lines 72 and 86.
Removing them throws ` error: Too many arguments for "Channel"` and I didn't manage to solve that. Any advice?
=> [unitaryHACK] Add type hints to `channels.py` (#16)

pulser/devices/_device_datacls.py, pulser/json/coders.py
Type checked on `_device_datacls.py` and `coders.py`. 
Was getting `Skipping analyzing module_name: found module but no type hints or library stubs` error on line 19 of `_device_datacls.py`, wasn't able to correct it, used `#type: ignore` to ignore the same.
=> Add type hints in `_device_datacls.py` and `coders.py` [unitaryHACK] (#16)

pulser/_seq_drawer.py, pulser/sequence.py, pulser/simulation/simulation.py, pulser/tests/test_sequence.py, pulser/tests/test_simulation.py
This pull request attempts to address #149.
**Details**
- It adds a condition `draw_phase_area` (default to `False`) in the `draw` method of a `Sequence` object. The `draw_sequence` function also has this argument.
- Based on this argument, it would allow to plot phase and area for each of the waveforms, where the values are in multiples of `pi`.
- Instead of writing "Phase" and "Area", it is written once in the title and then the symbols are used throughout to avoid consuming large space on the plot.
Since this is currently a draft, there is still some work to do regarding the placement of the text.
The output of running:
```
seq.draw(draw_phase_area=True)
```
on a sample sequence (the same sequence as shown in the issue) currently looks like this:
I would love to get any thoughts on …
=> Add phase and area text to pulse plot [unitaryHACK]

pulser/register.py
When drawing a `Register`, the size of half the blockade radius was changing depending on the system, due to an inconsistent transformation from "data" to "display" coordinates. This change avoids such a transformation, so the reported behaviour should disappear.
Closes #178 .
=> Fix variable circle size on Register.draw()

pulser/channels.py, pulser/devices/_device_datacls.py, pulser/json/coders.py, pulser/json/utils.py, pulser/parametrized/decorators.py, pulser/parametrized/paramabc.py, pulser/parametrized/paramobj.py, pulser/parametrized/variable.py, pulser/pulse.py, pulser/register.py, pulser/simulation/simresults.py, pulser/waveforms.py
- Makes existing type hints PEP 585 compliant, namely by using built-in generics whenever possible
- Further specifies some existing type annotations
- Normalizes style for `from __future__ import annotations` to be always separated by a blank line from the rest of the imports
=> Type annotation fixes

.mypy.ini, pulser/json/utils.py, pulser/parametrized/decorators.py, pulser/parametrized/paramabc.py, pulser/parametrized/paramobj.py, pulser/parametrized/variable.py, pulser/pulse.py, pulser/sequence.py, pulser/tests/__init__.py, pulser/waveforms.py
Now that almost all the source code is covered by type hints, we can configure `mypy` to disallow untyped definitions, which will enforce typing on all `def` statements.
This PR adds the few missing type hints (though mostly were redundant) so that this setting can be enabled without errors.
As the unit tests are not being typed, an exception is made for them. In order to do so, `pulser.tests` had to be seen as a module, so a `pulser/tests/__init__.py` was added.
=> Disallow untyped defs outside of tests

pulser/register.py, pulser/tests/test_register.py
Extends the range of the test to N = 6 atoms.
Disables centering in order to leave the innermost atom on (0,0).
Changes the order of atoms for consistency with N >= 7 atoms (spiral pattern).
Uses `device.min_atom_distance` instead of constant `4` in tests.
=> Enhanced max_connectivity() under 7 atoms

pulser/register.py, pulser/tests/test_register.py
For feedback: First attempt to enhance ValueError messages (see #148 and #157), starting with `register.py`.
Guidelines:
* Functional explanation of parameter
* Technical name of parameter
* Provided value of parameter
* Using "must" rather than any other verb
* No negation
* Using "less than / equal to / greater than" rather than any other expression
* Recall allowed values
* All sentences follow the same structure
=> Enhance ValueError messages (#148 and #157)

pulser/simulation/__init__.py, pulser/simulation/simconfig.py, pulser/tests/test_simconfig.py
Adds a `SimConfig` class to pulser to be used by a `Simulation` object. Contains noise settings, number of runs, system temperature... Part of the noisy simulations PR.
=> Add simconfig

pulser/sequence.py, pulser/tests/test_sequence.py
- Magnetic field can be set on a Sequence if working on the XY mode
- On an empty sequence, setting the magnetic field puts it into the XY mode
- When not specified, assumes a default of (0, 0, 1) G when entering the XY mode
=> Adding method to set the magnetic field on a Sequence

pulser/sequence.py, pulser/tests/test_sequence.py
The changes in #200 forgot to add serialization support. These changes store the call(s) in which the magnetic field is set, so that when a sequence is serialized and deserialized, it keeps the magnetic field information.
=> Include magnetic field in serialization

pulser/sequence.py, pulser/tests/test_sequence.py
Enforces a minimal duration for delays, equal to the minimal duration allowed by the channel (see #204).
Adds a corresponding test for 100% coverage.
=> Enforce minimal duration for delay (#204)

requirements.txt, setup.py
The `typing-extensions` package is necessary if using Python 3.7, so it's added to `requirements.txt` and `setup.py` as a version-dependent requirement.
=> Adds 'typing-extensions' to requirements for Python 3.7

pulser/_seq_drawer.py, pulser/sequence.py, pulser/tests/test_sequence.py, pulser/tests/test_waveforms.py, pulser/waveforms.py
- Adds a new waveform type, `InterpolatedWaveform`, which lets the user create a waveform by defining a set of interpolation points and an interpolator.
- Currently supports `interp1d` and `PchipInterpolator` from `scipy.interpolate`, with access to these interpolators optional arguments
- Adds support for drawing the interpolation points on top of the waveform in `Waveform.draw()`, `Pulse.draw()` and `Sequence.draw()`
=> New `InterpolatedWaveform` class

pulser/_seq_drawer.py, pulser/sequence.py, pulser/simulation/simulation.py, pulser/tests/test_sequence.py, tutorials/composition/Phase Shifts and Virtual Z gates.ipynb
The display of the phase shift information on the drawing of a sequence is a niche usecase, so it is turned into an optional on `Sequence.draw()` that defaults to `False`.
=> Make drawing of phase shift information optional

pulser/tests/test_waveforms.py, pulser/waveforms.py
=> `BlackmanWaveform.from_max_val()`: Move back to previous even duration when necessary (#218)

pulser/simulation/simresults.py, pulser/simulation/simulation.py, pulser/tests/test_simresults.py
These changes incorporate measurement errors into `CoherentResults`, such that:
- When calling `sample_state()`, the result automatically includes the measurement errors (i.e. `_sampling_with_detection_errors()` was incorporated in `sample_state()`)
- When calling `expect()`, it calculates the "pseudo-density matrices", corresponding to the state of the system post-measurement. When measurement errors are present, these are used instead of the state vectors
A few extra features were added in the process:
- The ability to calculate the pseudo-density matrix of the system at a given time is part of the parent class, as it is needed in both child classes now. The calculation might be expensive for large systems, so I'm caching them so that they're only computed once.
- The measurement errors …
=> Measurement errors incoporated into `CoherentResults`

pulser/simulation/simresults.py, pulser/tests/test_simresults.py
Fixes a bug regarding the computation of expectation values in the all basis via SimResults.expect().
=> Fixes bug with SimResults.expect()

pulser/tests/test_waveforms.py, pulser/waveforms.py
Although the original implementation of `BlackmanWaveform.from_last_val()` had negative values in mind, the changes introduced in #222 were designed with only positive values in mind. These changes serve to make those changes work for negative waveforms as well.
=> `BlackmanWaveform.from_last_val()` fully compatible with negative inputs

pulser/simulation/simulation.py, pulser/tests/test_simulation.py
This PR prevents the existing conflict between the setting of a custom initial state and the way we simulate state preparation errors, as described in #244.
Closes #244 .
=> Forbid combination of custom initial_state with state preparation errors

pulser/_version.py, pulser/simulation/simulation.py, pulser/tests/test_simulation.py
The error was caused by amp, det and phase samples replacing the old values instead of adding. That would be fine it two pulses with different addressing and basis could never write on the same samples, but with the introduction of noise sometimes a global pulse becomes local and a conflict might happen.
Since the amp, det and phase samples are always initialized to 0, it's fine to add instead of replacing.
I also added a unit test in test_simulation.py that the old code does not pass regarding this issue.
=> Fixed global-local overwriting bug and added test

pulser/register.py, pulser/tests/test_register.py
Minor fix : `Register.from_coordinates()`now has an additional optional argument to specify custom labels on each qubit. This change is applied to the `to_2D()`method
=> Custom labels

pulser/_seq_drawer.py, pulser/register.py, pulser/sequence.py, pulser/tests/test_sequence.py
`Sequence.draw()` now accepts a new boolean argument `draw_register` that defaults to `False`.
When `True`, the full register is shown after the pulse sequence. If an SLM mask is set, the masked qubits are shown as red crosses.
There are some points to discuss: 
1. The code is a bit redundant, as the register drawing part is copied from `Register.draw()`. One could think for example to split `Register.draw()` in two methods, the first returning an `ax` that could be used directly into `Sequence.draw()`. On the other hand, `Sequence` has the extra information on the SLM mask which is missing in `Register`, so I couldn't see a way to do that. 
2. Should the register drawing options (like blockade radius) be passed in `Sequence.draw()` as well? Or do we want to fall back on a set of default …
=> Added register drawing capabilities to Sequence.draw()

MANIFEST.in, pulser/_version.py
The C6_coeffs.json file was not being included in the `v0.4.0` distribution, this fixes that.
=> [HOTFIX] Include C6_coeffs.json file in dist

pulser/devices/_device_datacls.py, pulser/simulation/simulation.py, requirements.txt, setup.py
As detailed in #303 , the latest version of `numpy` is not compatible with `qutip`, so I'm restricting the `numpy` version for now.
Additionally, the latest version of `mypy` also seems to have raised a couple `typing` errors, which i'm fixing here too.
Fixes #303.
=> [Hotfix] Restricting numpy version to fix qutip incompatibility 

pulser/channels.py, pulser/devices/_device_datacls.py, pulser/devices/_mock_device.py, pulser/sequence.py, pulser/tests/test_channels.py, pulser/tests/test_devices.py, pulser/tests/test_sequence.py
Test coverage is at 100%, but more specific tests should be added once devices with channels using these quantities are defined (see #297).
Closes #296 .
=> Buffer times for retargeting and phase jumps

pulser/_seq_drawer.py, pulser/parametrized/decorators.py, pulser/pulse.py, pulser/sequence.py
Fix for #310 , which improves the type hints of decorators and fixes the `mypy` errors arising from it. As a result, the full type hints for `Pulse` have been brought back, after they were changed on #242.
=> Decorator type hints

pyproject.toml
Since we don't use the default `black` line length, only setting the `isort` profile to `black` will make `isort` go up to the 88 character limit, which causes an incompatibility with our custom 79 character limit. Adding an explicit `line_lenght=79` parameter to the `isort` config fixes this.
=> Changing the line length for the `isort` config

pulser/register/register.py, pulser/waveforms.py, requirements.txt, setup.py
`qutip` 4.6.3 now supports the latest version of `numpy`, so I'm removing the restriction that `numpy < 1.22` and rather place it on qutip to be `>=4.6.3`(ie it's latest version).
This effectively reverses the hotfix introduced in #304 , which was needed due to an update of `numpy` that `qutip` did not support.
=> Removing restriction on numpy version following qutip's update

pulser/_seq_drawer.py, pulser/register/_reg_drawer.py, pulser/register/base_register.py, pulser/register/mappable_reg.py, pulser/register/register_layout.py, pulser/register/suspended_reg.py, pulser/sequence.py, pulser/simulation/simulation.py, pulser/tests/test_json.py, pulser/tests/test_paramseq.py, pulser/tests/test_register.py, pulser/tests/test_register_layout.py, pulser/tests/test_sequence.py, pulser/tests/test_simulation.py
Creates the `MappableRegister` class which enables the build of multiple sequences for the same `Sequence` instance, with the register being defined at build time.
=> Mappable Register

pulser/sequence.py, pulser/tests/test_json.py
A sequence that was built from a sequence with a mappable register was going back to having a mappable register after serialization and deserialization. This was because the first call that is used to initialise the sequence was not being updated when the register is defined.
This PR adds the fix and a test for this scenario.
=> Hotfix: Register from mappable register going back to mappable in Sequence

pulser/simulation/simulation.py
This PR adds the option for updating `runs` and `samples_per_run` when using the `Simulation.add_config()` method, which has been rising recently as something users want to include.
I also added some comments for future reading.
=> Update runs and samples per run.

pulser/json/supported.py, pulser/parametrized/paramobj.py, pulser/parametrized/variable.py, pulser/sequence.py, pulser/simulation/simulation.py, pulser/tests/test_parametrized.py, pulser/tests/test_paramseq.py
- Added new operators to `OpSupport`
- Removed `Variable.__len__()` to allow for applications of numpy ufuncs without unpacking
- Blocked reference to channels and measurement basis with variables
=> Changes for compatibility with upcoming export format

pulser/sampler/__init__.py, pulser/sampler/noise_model.py, pulser/sampler/sampler.py, pulser/sampler/samples.py, pulser/simulation/noises.py, pulser/tests/test_sampling_noises.py, pulser/tests/test_sequence_sampler.py
- Separates the specific noise definitions from general noise objects to isolate `pulser.sampler` and `pulser.simulation`
- Adds missing license headers
=> Updates to `pulser.sampler`

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/register/base_register.py, pulser-core/pulser/register/mappable_reg.py, pulser-core/pulser/register/register.py, pulser-core/pulser/sequence.py, tests/test_json.py
Adds a `layout` property to both `Register` and `MappableRegister` so that the underlying layout is accessible in the same way for both classes.
=> Uniform access to the layout in Register and MappableRegister

pulser-simulation/pulser_simulation/simulation.py, tests/test_simulation.py
This fixes a bug that appeared when simulating a sequence where an SLM mask has a target that is never addressed by the local channel. The accompanying test is an example where a `KeyError` would be thrown without this change.
=> Bugfix in simulation with SLM mask

.github/workflows/publish.yml
After uploading a new release to PyPI, this step will repeatedly attempt to download it. This will ensure that the subsequent tests will run after the new release is properly deployed.
=> Add step in publish workflow to confirm deployment

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/devices/_devices.py, pulser-core/pulser/devices/_mock_device.py, pulser-core/pulser/sequence/sequence.py, tests/conftest.py, tests/test_sequence.py
I realized that currently we can program the SLM mask for every device, but not every device supports it. This makes the support  of the SLM mask (or lack thereof) explicit in the device configuration.
=> Make SLM mask support device dependent

docs/source/apidoc/core.rst, pulser-core/pulser/channels.py, pulser-core/pulser/devices/__init__.py, pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/devices/_mock_device.py, pulser-core/pulser/json/supported.py, pulser-core/pulser/register/register.py, pulser-core/pulser/sequence/sequence.py, tests/test_devices.py, tests/test_json.py, tests/test_register.py, tests/test_sequence.py
Prior to this PR, a `Device` instance was the only way to encode the device specs. Furthermore, these specs were not meant to be user defined but rather import from the `pulser.devices` module.
This PR makes the declaration of custom devices properly validated and introduces the concept of `VirtualDevice` - a device that is not realistic and thus is meant to be used only in emulators.
- Creates the `BaseDevice` ABC and its subclasses, `Device` and `VirtualDevice`
- Turns `MockDevice` into a `VirtualDevice` instance
- Adds checks to the initialisation parameters so that user-definition is properly validated
- Introduces full serialization for `VirtualDevice`
=> Introducing the `Device` vs `VirtualDevice` distinction

pulser-core/pulser/register/register_layout.py, pulser-core/pulser/register/special_layouts.py, tests/test_register_layout.py
Adds an optional `slug` parameter to the `RegisterLayout` to allow easier identification of layouts.
=> Adding optional slug to RegisterLayout

pulser-core/pulser/sequence/_seq_str.py, tests/test_sequence.py
As the targets of a channel are stored in a `set`, printing a sequence gave variable results because there was no order in the targets. With this change they are sorted and thus printing the same sequence will always give the same result.
=> Sorting targets in Sequence.__str__() for consistency

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/devices/_mock_device.py, pulser-simulation/pulser_simulation/simulation.py, tests/test_devices.py
To accompany upcoming changes in the abstract representation schema, the `Device.interaction_coeff_xy` parameter type is now `Optional[float]` and defaults to `None`. If there is a `Microwave` channel in the device, however, it is enforced to be a `float`.
=> Make `Device.interaction_coeff_xy` optional by default

pulser-simulation/requirements.txt
Qutip was failing to install on Python 3.11 (see https://github.com/qutip/qutip/issues/2036) . With the latest patch, this has been fixed.
=> Update `qutip` version to include latest patch

docs/source/index.rst, docs/source/tutorials/output_mod_eom.nblink, pulser-core/pulser/channels/eom.py, pulser-core/pulser/sampler/sampler.py, pulser-core/pulser/sampler/samples.py, pulser-core/pulser/sequence/_schedule.py, pulser-core/pulser/sequence/_seq_str.py, pulser-core/pulser/sequence/sequence.py, tests/test_paramseq.py, tests/test_sequence.py, tests/test_sequence_sampler.py, tests/test_simulation.py, tutorials/advanced_features/Output Modulation and EOM Mode.ipynb
- Adds EOM mode operation to `Sequence`
- Incorporates EOM mode modulation in the `sampler`
- Adds a tutorial on output modulation and EOM mode operation (purposefully stored without output; to check the output, see the readthedocs CI build)
Closes #367 , #418.
=> Incorporate EOM mode operation in `Sequence`

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/register/mappable_reg.py, pulser-core/pulser/register/register_layout.py, pulser-core/pulser/register/special_layouts.py, pulser-core/pulser/sequence/sequence.py, tests/test_devices.py, tests/test_register_layout.py, tutorials/advanced_features/Register Layouts.ipynb
This PR changes slightly how a register can be defined from a layout by the introducing the **maximum layout filling fraction** of a device.
Before:
- The maximum filling fraction was implicitly assumed to be 50% -> the layout knows the maximum amount of atoms it can hold
- When defining a register on a layout, it checked right away if the number of atoms did not go over 0.5 * `number_of_traps`
- When validated against a Device, a layout could have a maximum of (2 * `max_atom_num`) traps
Now:
- The maximum filling fraction is determined by the device -> the layout no longer knows the maximum amount of atoms it can hold
- When defining a register on a layout, it only checks  if the number of atoms does not go over the `number_of_traps`
- When validated against a Device, there is no longer …
=> Maximum Layout Filling Fraction

pulser-core/pulser/register/register_layout.py, tests/test_register_layout.py
Fixes the following UT in *test_register_layout.py* which is newly failing:
```python
def test_creation(layout, layout3d):
with pytest.raises(
ValueError, match="must be an array or list of coordinates"
):
RegisterLayout([[0, 0, 0], [1, 1], [1, 0], [0, 1]])
```
This has happened on trying to merge #406 on the job https://github.com/pasqal-io/Pulser/actions/runs/3741008851/jobs/6350057707, only on Python 3.11.1, which may have changed the behavior of creating numpy arrays with inconsistent list sizes.
=> Fix UT bug creating wrong numpy array

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/test.yml
By default, when a job in a Github Actions `matrix`, all other pending jobs are cancelled. This has two major drawbacks:
- It prevents checking whether the issue is specific to a single version or OS
- It makes re-running failed jobs take longer because the cancelled jobs have to be re-run too
These changes should change this behaviour. The potential drawback is that resources will be wasted if there is indeed a bug that makes all jobs fail, but this shouldn't happen on extensive workflows like `test` because they screened by leaner workflows like `build` - it is highly unlikely that something would get past `build` and completely fail on `test`.
=> Disable `fail-fast` on `matrix` jobs

.readthedocs.yml
As we have RTD automatically build the docs, sometimes there are warnings we miss that could have let us know something is not quite right.
Since our build runs without warnings under normal circumstances, we can let it fail in the presence of warnings so that we can catch them.
=> Enable RTD fail on warning

docs/requirements.txt, pulser-core/requirements.txt
I have deleted the requirement `jsonschema==4.4.0`.
Closes #454
=> Delete pinning jsonschema to version 4.4.0

pulser-core/pulser/channels/base_channel.py, pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/json/coders.py, pulser-core/pulser/json/supported.py, pulser-core/pulser/sequence/_schedule.py, pulser-core/pulser/sequence/sequence.py, tests/test_devices.py, tests/test_sequence.py
These changes are inconsequential for the functioning of `pulser-core` in isolation, but facilitate the subclassing of certain classes, which is useful for external projects and extensions.
=> Facilitating the subclassing of `Channel`, `BaseDevice` and `Sequence`

pulser-core/pulser/sequence/_decorators.py, tests/test_paramseq.py
When validating the arguments to calls where the arguments are potentially parametrized, there was a check for recursiveness for cases where e.g a parametrized element is inside an iterable. This check relied on a type check of the kind  `isinstance(x, Iterable)`, which essentially relied on the existence of an `__iter__` method in the object. This posed two issues:
1. Some objects are iterable because they define a `__getitem__` but not an `__iter__`
2. Crucially, some objects (in particular 0-D numpy arrays) have an `__iter__` method but then raise an error when it is called.
Because of these issues, I propose we replace the type check with a duck typing approach, where we simply try to iterate over the object and handle the case where it fails with a `try...except` block. This fixes …
=> Replace Iterable type checking in variable validation

pulser-core/pulser/channels/base_channel.py, pulser-core/pulser/channels/eom.py, tests/test_channels.py, tests/test_eom.py
I have set the upper bound to `MODBW_TO_TR*1e3` because this guarantees that the rise time `int(MODBW_TO_TR*1e3/mod_bandwidth)` is always above or equal to 1.
=>  Set an upper bound on the supported modulation bandwidth

pulser-pasqal/pulser_pasqal/__init__.py, pulser-pasqal/pulser_pasqal/job_parameters.py, pulser-pasqal/pulser_pasqal/pasqal_cloud.py, pulser-pasqal/requirements.txt, tests/test_pasqal.py
The PulserPasqal packge has an old version of the cloud-sdk. This MR bumps the version and implements the required interface for the latest version.
=> Update Pulser-Pasqal to the latest cloud-sdk syntax

pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
- Enables `Sequence.switch_device()` to be called on parametrized sequences
- Adds checks for `interaction_coeff_xy` and `min_retarget_interval` (when relevant)
- Small code refactoring
=> Updates to Sequence.switch_device()

.github/workflows/test.yml
The CI test runs on `windows-os` occasionally fail due claiming "This probably means that Tcl wasn't installed properly.". 
If I understand correctly, this happens when matplotlib is involved, as it tries to use a backend for plotting that requires Tcl, which apparently is poorly installed on some of Github's Windows runners. 
To circumvent this, we can set the backend to `agg`, which no longer requires Tcl and so should work every time.
Note: I'll be temporarily enabling the `full-tests` workflow to run on this PR to check things are running smoothly. I'll then revert that change before merging.
=> Fix for sporadic CI fail on Windows

pulser-core/pulser/json/abstract_repr/deserializer.py, pulser-core/pulser/json/exceptions.py, pulser-core/pulser/register/register_layout.py, tests/test_abstract_repr.py, tests/test_register_layout.py
- Creates `DeserializeDeviceError` and makes it the only error raised by `deserialize_device()`
- Adds an additional check to `RegisterLayout()` to forbid duplicates in trap coordinates
Fixes #478 .
=> Implement custom exception for device deserialization

pulser-simulation/pulser_simulation/simresults.py, tests/test_simresults.py
Skip `ignore_global_phase` if the state is a density matrix state.
raise a not ImplementedError if the basis is `digital` or `all basis`
Fixes #493
=> Adapt CoherentResults.get_state() for density matrix states

pulser-simulation/pulser_simulation/simulation.py
The changes don't impact simulations in Pulser, because `samples_obj` are created using `sampler.sample()` and thus `samples_obj._ch_obj` is the same as `_seq.declared_channels`.
However, it makes more sense to take the `ch_obj` from the samples as it doesn't rely in an underlying sequence being stored within the `Simulation` instance.
=> Minor changes for extensions of Simulation

pulser-core/pulser/json/abstract_repr/serializer.py, pulser-core/pulser/register/mappable_reg.py, pulser-core/pulser/sequence/_decorators.py, pulser-core/pulser/sequence/_seq_drawer.py, pulser-core/pulser/sequence/_seq_str.py, pulser-core/pulser/sequence/sequence.py, tests/test_abstract_repr.py, tests/test_register_layout.py, tests/test_sequence.py, tutorials/advanced_features/Register Layouts.ipynb
- I propose to do it by defining a default `Sequence._register` if the provided register is a `MappableRegister`, mapping each qubit id from the `qubit_ids` of the mappable register with the trap of same index in the `layout` of the mappable register.
- `_register` is used as a dummy register during all the operations prior to the `build` operation.
- `layout` of the mappable register is given as an optional parameter of `_register`, such that it can be used in `build` to perform the same operation as before.
Closes #502
=> Impose qubit order in MappableRegister

pulser-simulation/pulser_simulation/simresults.py, tests/test_simulation.py
- Fixes #352 
- Handle eps_p = eps = 0 case
=> Fix SPAM errors introducing overhead

pulser-core/pulser/sampler/samples.py, pulser-core/pulser/sequence/_schedule.py, pulser-simulation/pulser_simulation/simulation.py, tests/test_sequence_sampler.py, tests/test_simulation.py
- Allows for emulation of sequences with only delays by adding `intial_targets` information to `ChannelSamples`
- Fixes determination of `max_step` in `QutipEmulator.run()` when there is no non-zero pulse
=> Fixes for emulation of empty sequences 

pulser-pasqal/requirements.txt
`pydantic` is installed as a dependency of `pasqal-cloud`. The latest release of `pasqal-cloud` handles this issue, but that update is currently under review in #541 and might still take a bit to merge.
This will temporarily fix the CI tests, but it should be reverted in #541.
=> Temporarily pin pydantic to fix broken CI

pulser-core/pulser/channels/base_channel.py, pulser-core/pulser/channels/dmm.py, pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/json/supported.py, pulser-core/pulser/register/register_layout.py, pulser-core/pulser/register/traps.py, pulser-core/pulser/register/weight_maps.py, pulser-core/pulser/sampler/sampler.py, pulser-core/pulser/sampler/samples.py, pulser-core/pulser/sequence/_schedule.py, pulser-simulation/pulser_simulation/simulation.py, tests/test_channels.py, tests/test_dmm.py, tests/test_json.py, tests/test_sequence_sampler.py, tests/test_simulation.py
=> Special handling of samples from a DMM channel

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/devices/_devices.py, pulser-core/pulser/devices/_mock_device.py, pulser-core/pulser/json/abstract_repr/deserializer.py, pulser-core/pulser/json/abstract_repr/schemas/device-schema.json, pulser-core/pulser/json/abstract_repr/schemas/sequence-schema.json, pulser-core/pulser/json/abstract_repr/serializer.py, pulser-core/pulser/register/base_register.py, pulser-core/pulser/register/mappable_reg.py, pulser-core/pulser/register/register_layout.py, pulser-core/pulser/sequence/sequence.py, tests/test_abstract_repr.py, tests/test_devices.py, tests/test_dmm.py, tests/test_sequence.py, tests/test_sequence_sampler.py, tests/test_simulation.py
=> Abstract representation support for new DMM features

docs/requirements.txt, pulser-core/pulser/json/abstract_repr/validation.py, pulser-core/requirements.txt, tests/test_abstract_repr.py
I suspect this is what's causing problems in the docs build, so I'm switching to the reference system introduced in `jsonschema 4.18`.
=> Update to jsonschema > 4.18, Sphinx < 7

pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
In switch_device, resets to an empty string the `ch_match_err` and `strict_error_message` if they were generated while trying to match the current channel with the channels of the new device and a match has been found. 
If no match was found for a channel, the ch_match_err and the strict_error_message are still kept and are raised at the end of the for loop. 
Closes #579
=> Bug Fix: error message in switch_device

pulser-core/requirements.txt
It seems that `matplotlib 3.8` does two disruptive things to our CI workflow:
1. It introduces type-hints
2. It drops support for python 3.8
I briefly looked into the changes that it will take to make our current code pass the `mypy` checks and I think some warrant using`type:ignore` . However, these `type:ignore`s will then be seen as "unused" when using `matplotlib < 3.8`, which is a necessity if `python == 3.8`.
Also, I would prefer that all python versions have access to the same matplotlib version, so for now I'll just restrict `matplotlib` to be < 3.8. I don't expect us to miss out on any functionality, but we can always revaluate. Once we drop support for python 3.8, we can maybe lift this restriction too.
=> Pin matplotlib < 3.8

pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
Finalizing resolution from #579, in the last MR #580 two tests were the same, whereas one was intended to be for strict=False and the other for strict=True.
=> Fix switch device err message

pulser-pasqal/pulser_pasqal/backends.py, tests/test_pasqal.py
The default sampling rate, inherited from `EmulatorConfig`  defaults, is 1.
If I am not mistaken, this translates to `dt=1` for the EmuTN job runned by cloud services, which is not a viable value.
I open this MR not for a blind merge, but rather to make sure the above interpretation of `sampling_rate` for EmuTnBackend is right, and reflect on a good default value.
=> Change EmuTN default sampling rate

pulser-core/pulser/backend/remote.py, pulser-pasqal/pulser_pasqal/pasqal_cloud.py, pulser-pasqal/requirements.txt, tests/test_backend.py, tests/test_pasqal.py
=> Use jobs order provided by the cloud

pulser-core/pulser/devices/_device_datacls.py, tests/test_devices.py
As suggested by @HGSilveri:
Add two new methods to `Device`:
As discussed, returns a boolean and not an error.
register_is_from_calibrated_layout works with BaseRegister (hence Register and Register3D) and MappableRegister (always has a layout in this case) because the type of the register in a sequence can be of type one of these two types. 
Closes #577
=> Adding register_is_from_calibrated_layout and is_calibrated_layout to Device

docs/source/apidoc/core.rst, docs/source/apidoc/simulation.rst, pulser-simulation/pulser_simulation/qutip_result.py
=> Add DMM, methods of RegisterLayout inherited from Traps, Result

pulser-core/pulser/waveforms.py, tests/test_waveforms.py
=> Add adaptative rounding in InterpolatedWaveform

pulser-core/pulser/backend/qpu.py, pulser-core/pulser/backend/remote.py, pulser-pasqal/pulser_pasqal/backends.py, pulser-pasqal/pulser_pasqal/pasqal_cloud.py, pulser-pasqal/requirements.txt, tests/test_backend.py
=> Add `wait` option to remote backends

pulser-core/pulser/sequence/sequence.py, tests/test_paramseq.py
I stumbled upon this bug when trying to make EOM pulses with a parametrized phase.
=> [FIX] Allow parametrized phase in EOM mode

pulser-core/pulser/register/register.py, tests/test_json.py, tests/test_register.py, tests/test_register_layout.py, tutorials/creating_sequences.ipynb
- Introduces `Register.rotated()`, which returns a new instance instead of rotating in place
- Deprecates `Register.rotate()` 
Closes #628 .
=> Replace `Register.rotate()` with `Register.rotated()`

pulser-core/pulser/register/register.py, tests/test_register.py, tests/test_register_layout.py
Following deprecation in v0.17.0.
=> Remove `Register.rotate()`

pulser-simulation/pulser_simulation/hamiltonian.py, tests/test_simulation.py
Grabbing the hanging fruit: everything was already here to enable simulation in digital mode.
=> Enable digital simulation

pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
- Blocks `Sequence.add()` on DMM channels
- Blocks `Sequence.add_dmm_detuning()` on non-DMM channels
I think having one unique way of adding Pulses to DMM and non-DMM channels is preferable but let me know if you think otherwise
=> Block add() on DMM channels

.pre-commit-config.yaml, pulser-core/pulser/backend/noise_model.py, pulser-simulation/pulser_simulation/qutip_backend.py, pulser-simulation/pulser_simulation/simconfig.py, pulser-simulation/pulser_simulation/simulation.py, tests/test_backend.py, tests/test_simconfig.py, tests/test_simulation.py
This PR removes the already deprecated:
- `dephasing_prob`
- `depolarizing_prob`
- `effective_noise_probs`
=> Remove deprecated noise arguments

pulser-core/pulser/backend/noise_model.py, pulser-simulation/pulser_simulation/hamiltonian.py, pulser-simulation/pulser_simulation/simconfig.py, pulser-simulation/pulser_simulation/simresults.py, pulser-simulation/pulser_simulation/simulation.py, tests/test_backend.py, tests/test_simconfig.py, tests/test_simulation.py
The tutorials on noisy simulation should be updated accordingly but I'll leave that for another PR as I think we'll need to do a deeper revision. I'm still noting it down in #658 so we don't forget about it.
Closes #673 .
=> Adding relaxation noise channel

.github/workflows/test.yml
`macos-latest` no longer supports Python 3.8 and 3.9 so I'm using `macos-13` for these versions instead.
=> Fix CI tests on "macos" for python < 3.10

pulser-core/pulser/devices/_device_datacls.py, tests/test_abstract_repr.py, tests/test_devices.py
These fields will be necessary to replicate QPU validation locally, as proposed in #661. I want to ship them already in the v0.18 release so that we can then change them in `AnalogDevice` on v0.19, where we will also tackle #661.  
I'm including these fields in the JSON schema update of #676 , so that PR has to be merged before this one.
=> Add missing QPU validation fields to the Device class

pulser-core/pulser/json/supported.py, pulser-core/pulser/register/__init__.py, pulser-core/pulser/register/register.py, pulser-core/pulser/register/special_layouts.py, tests/test_json.py, tests/test_register.py, tests/test_register_layout.py
Addition of classes to the special layouts :
RectangularLatticeLayout to be able to play with x and y spacing. Now SquareLatticeLayout inherits from it. Don't know how to deal with the print change, we can keep rectangular for a square. (one test fails that compares the strings)
TriangularLatticeLayoutRectShape to have triangular lattice in a rectangular layout
RandomLayout that generates a random layout for a given number of traps (limited number of iterations)
mypy failed because of no type defintion of an empty list in RandomLayout.
=> Rectangular lattice register and layout

pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
This has been requested more than once, so I figured we could add a proper way to do it.
=> Add option to switch the Sequence register

pulser-core/pulser/channels/dmm.py, pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/math/__init__.py, pulser-core/pulser/math/abstract_array.py, pulser-core/pulser/parametrized/paramobj.py, pulser-core/pulser/parametrized/variable.py, pulser-core/pulser/pulse.py, pulser-core/pulser/register/_coordinates.py, pulser-core/pulser/register/base_register.py, pulser-core/pulser/register/register_layout.py, pulser-core/pulser/register/weight_maps.py, pulser-core/pulser/sampler/samples.py, pulser-core/pulser/sequence/_schedule.py, pulser-core/pulser/sequence/sequence.py, pulser-core/pulser/waveforms.py, pulser-simulation/pulser_simulation/hamiltonian.py, pulser-simulation/pulser_simulation/simulation.py
Modify `pulser-core` to support all current features of differentiable `torch` backend.
=> Add support for pulser-diff backend

pulser-core/pulser/channels/eom.py, pulser-core/pulser/json/abstract_repr/schemas/device-schema.json, pulser-core/pulser/sequence/_schedule.py, pulser-core/pulser/sequence/sequence.py, tests/test_abstract_repr.py, tests/test_eom.py
=> Add lightshift coefficients to RydbergEOM

.github/workflows/test.yml, tests/test_pulse.py
This UT was passing on Mac and Ubuntu but failing on Windows.
=> Fix OS-precision-dependent unit test

pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
Although we can't change the phase of the pulses added to a DMM channel, the phase was still being adjusted according to the changes to the phase reference. Since the phase of the DMM channel's pulses is irrelevant, we should just keep it at zero instead.
=> Ignore the phase reference on the DMM channel's pulses

pulser-simulation/pulser_simulation/hamiltonian.py
=> Defining dephasing and depolarizing operators with projectors

.github/workflows/ci.yml, tests/test_simulation.py
=> Fix failing pipeline for test of relaxation noise in qutrit state

pulser-core/pulser/channels/base_channel.py, pulser-core/pulser/noise_model.py, pulser-simulation/pulser_simulation/hamiltonian.py, pulser-simulation/pulser_simulation/qutip_result.py, pulser-simulation/pulser_simulation/simconfig.py, pulser-simulation/pulser_simulation/simresults.py, pulser-simulation/pulser_simulation/simulation.py, tests/test_noise_model.py, tests/test_result.py, tests/test_simconfig.py, tests/test_simresults.py, tests/test_simulation.py
Implements the "leakage" noise. When "leakage" is provided as a `noise` in the `SimConfig`:
- Adds a state "x" in the eigenbasis of the computation.
- Rebuilds, the basis, dim, op_matrix associated to the computational basis
- Rebuilds the `operators` in Hamiltonian (see `construct_hamiltonian`) since they changed size
- Modifies the initial state of QutipEmulator (defaults to "all-ground")
=> Add leakage

pulser-core/pulser/backend/remote.py, pulser-pasqal/pulser_pasqal/pasqal_cloud.py, tests/test_backend.py, tests/test_pasqal.py
- Stop raising an Exception if one of the job of the batch has no results after fetching. 
- Stop raising an exception when fetching results if the status of the batch is a termination status.
Currently if one of the job of a batch fails, it is impossible to retrieve the results for any jobs of the batch - this raises an exception. In this PR, I suggest instead to add `None` to the list of results for that submission when a job has no results. I don't know if returning None is the most idiomatic way to do this in pulser; I also contemplated creating a new subclass of `Result` called `EmptyResult` but I wanted to gather some feedback before going for that because it would imply some refactoring of the `Result` class and I'm not entirely convinced it would bring much.
=> [FEAT] Handle batches with partial results

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/json/abstract_repr/deserializer.py, tests/test_abstract_repr.py
- Cast parameters being string formatted to `float()` to avoid errors
- Allow deserialization of noise models serialized with `pulser-core<0.20` (ie prior to the `NoiseModel` interface rework)
This is unorthodox but we'll need to release this hotfix as if it were a scheduled release to include #733 .
=> Restore backwards compatibility with `pulser-core<0.20`

pulser-core/pulser/math/__init__.py, pulser-core/pulser/waveforms.py, tests/test_waveforms.py
Rounding errors in the generation of a `RampWaveform`'s samples could lead the edge values to lie outside of the range of the `start`and `stop` values. This ensures they stay within said range.
=> Fix rounding error in RampWaveform samples

tutorials/simulating_sequences.ipynb
The original formulas was normalized using np.tan(np.pi / L). However, this is not correct, as can be checked by computing the normalization between the distances between the atoms (one does not get R_interatomic).
Here is a quick code to show the issue:
```python
import numpy as np
def setup_coords(L, R_interatomic, fn=np.sin):
coords = (
R_interatomic
/ (2 * fn(np.pi / L))
* np.array(
[
(np.cos(theta * 2 * np.pi / L), np.sin(theta * 2 * np.pi / L))
for theta in range(L)
]
)
)
distances = np.linalg.norm(coords - np.roll(coords, shift=1, axis=0), axis=1)
return distances
L = 5
R_interatomic = 1
print("sin:", setup_coords(L, R_interatomic, fn=np.sin))
print("tan:", setup_coords(L, R_interatomic, fn=np.tan))
```
which gives
```python
sin: [1. 1. 1. 1. 1.]
tan: [0.80901699 0.80901699 …
```
=> Fix normalisation in ring of atoms

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/json/abstract_repr/schemas/device-schema.json, tests/test_abstract_repr.py, tests/test_devices.py
- Adds three new layout-specific parameters to `BaseDevice`:
- `optimal_layout_filling`: An optional value for the fraction of a layout that should be filled with atoms.
- `min_layout_traps`: The minimum number of traps a layout can have.
- `max_layout_traps`: An optional value for the maximum number of traps a layout can have.
- Includes these new values in `BaseDevice.validate_layout()` 
Closes #749 .
=> Add layout-restricting parameters to BaseDevice

pulser-core/pulser/json/abstract_repr/schemas/device-schema.json, pulser-core/pulser/json/abstract_repr/schemas/layout-schema.json, pulser-core/pulser/json/abstract_repr/schemas/noise-schema.json, pulser-core/pulser/json/abstract_repr/schemas/register-schema.json, pulser-core/pulser/json/abstract_repr/schemas/sequence-schema.json, pulser-core/pulser/json/abstract_repr/validation.py, pulser-core/requirements.txt, tests/test_abstract_repr.py
=> Attempt to compare pulser versions when abstract repr validation fails

pulser-core/pulser/register/_layout_gen.py, pulser-core/pulser/register/register.py, tests/test_register.py, tutorials/advanced_features/Backends for Sequence Execution.ipynb
- Adds an algorithm for defining the layout trap coordinates from a set of atomic coordinates
- Defines `Register.with_automatic_layout(device: Device)`, which allows the user to get an automatically generated layout that obeys the `device` constrains from any register
Closes #748 .
=> Incorporate automatic layout generation in `Register`

pulser-core/pulser/channels/base_channel.py, pulser-core/pulser/channels/channels.py, pulser-core/pulser/channels/dmm.py
The old, prettier __repr__ assigned manually is now accessed trough the __str__() method of the Channel class, as proposed in issue #767
=> Change Channel.__repr__() to the default from dataclass

pulser-core/pulser/channels/base_channel.py, pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/json/abstract_repr/schemas/device-schema.json, pulser-core/pulser/noise_model.py, pulser-simulation/pulser_simulation/hamiltonian.py, pulser-simulation/pulser_simulation/simconfig.py, tests/test_abstract_repr.py, tests/test_channels.py, tests/test_simconfig.py, tests/test_simresults.py, tests/test_simulation.py
- Adds information of the beam's propagation direction to `Channel` 
- Makes finite-waist effects depend on the position relative to the optical axis
- Makes amplitude fluctuations occur from run to run instead of pulse to pulse
- Fixes the transfer of `laser_waist` between `NoiseModel` and `SimConfig`
- Starts adding the `pulser_version` to serialized devices 
Note: To avoid disruptions for serialized devices between different versions, `propagation_dir` is defaulting to `None` in all channels and `QutipEmulator` is assuming using `propagation_dir=(0,1,0)` whenever it encounter `None`. In a future version, it would make more sense to change the default `propagation_dir` of `Global` channels to be `(0,1,0)` and remove this assumption from `QutipEmulator`. 
Fixes #712
=> Fixes to the amplitude noise implementation

pulser-core/pulser/sequence/_schedule.py, pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
Adds the method `estimate_add_delay` to Sequence.
Has the same signature as the `add` method.
Takes into account AOM and EOM Pulses (raise a Warning if the Pulse added is not Constant, with amplitude and detuning equal to the rabi_fres and detuning_on of the EOM Block)
Raise a Warning if the duration of the added Pulse exceeds the duration of the Sequence.
Fixes #761
=> Add method to Sequence to estimate delay introduced before adding pulse

pulser-core/pulser/math/abstract_array.py, pulser-core/pulser/register/base_register.py, tests/test_channels.py, tests/test_eom.py, tests/test_math.py, tests/test_parametrized.py, tests/test_pulse.py, tests/test_register.py, tests/test_sequence.py, tests/test_sequence_sampler.py, tests/test_waveforms.py
- Adds `AbstractArray.is_differentiable`, which checks if the stored array is a tensor with `requires_grad=True`
=> Add shortcut to find out if an AbstractArray is differentiable

tests/test_simulation.py
For some unknown reason, this test started failing with the release of SciPy 1.15.
=> Fix unit test broken by scipy 1.15

pulser-core/pulser/json/abstract_repr/schemas/sequence-schema.json, pulser-core/pulser/json/abstract_repr/signatures.py, pulser-core/pulser/math/__init__.py, pulser-core/pulser/parametrized/paramobj.py, tests/test_abstract_repr.py, tests/test_parametrized.py
=> Add tanh function to ParamObj

pulser-core/pulser/sequence/_seq_drawer.py, tests/test_sequence.py
The drawing of the interpolated points on a DMM channel failed because it was assuming the amplitude would always be plotted. This solution may be overkill but at least it does not make any assumptions anymore
=> Fix drawing of interpolated waveform on DMM

pulser-core/pulser/sequence/sequence.py
We used to be saving the quantities per qubit instead of the legend of the qubit quantities in "myfile_per_qubit_legend.png". This is solved with this PR. No need to be a hotfix.
=> Fix drawing of legends for local qubit quantities

pulser-core/pulser/json/abstract_repr/serializer.py, pulser-core/pulser/sequence/sequence.py, tests/conftest.py, tests/test_abstract_repr.py, tests/test_sequence.py
This proposes to change `Sequence.phase_shift` to accept not setting a specific target, so that the phase shift is applied to all qubits in the `Register`.
I noticed that it wouldn't raise an error if no targets were supplied in the current version. Instead, it just wouldn't have any effect as no targets have been selected. This behavior changes if this PR is merged. I don't foresee backwards compatibility issues because of it, because the function shouldn't have been used if no targets were supplied.
This PR Closes #827
=> Add global phase shift

pulser-core/pulser/backend/config.py, tests/test_backend.py
Introduces the `_enforce_expected_kwargs` class variable to choose whether a warning is raised when receiving an unexpected parameter or not. Sets this to `False` in `EmulationConfig`
=> Allow additional parameters in EmulationConfig without a warning

pulser-core/pulser/backend/default_observables.py, pulser-core/pulser/backend/operator.py, pulser-core/pulser/backend/state.py, pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/exceptions/__init__.py, pulser-core/pulser/exceptions/base.py, pulser-core/pulser/exceptions/sequence.py, pulser-core/pulser/exceptions/serialization.py, pulser-core/pulser/json/abstract_repr/deserializer.py, pulser-core/pulser/json/abstract_repr/serializer.py, pulser-core/pulser/json/abstract_repr/validation.py, pulser-core/pulser/json/exceptions.py, pulser-core/pulser/json/supported.py, pulser-core/pulser/json/utils.py, pulser-core/pulser/parametrized/paramobj.py, pulser-core/pulser/sequence/sequence.py, pulser-core/pulser/waveforms.py, tests/conftest.py, tests/pulser_simulation/test_qutip_state_op.py, tests/test_abstract_repr.py, tests/test_backend_abstract_repr.py, tests/test_devices.py, tests/test_exceptions.py, tests/test_json.py
Resolves #831. In #828, we reworked exceptions during the constructions of sequences. Let's now apply this design to (de)serialization.
=> [DevEx] Rework (de)serialization exceptions

pulser-core/pulser/waveforms.py, tests/test_waveforms.py
Currently, defining an InterpolatedWaveform with both values and times as Variable fail, because the variable _values is not instantiated prior to the evaluation len(times) == len(values) in _check_values_times.
This fixes the issue ~and improves the tests: both numpy arrays and Variables have the attribute `size`, so we can actually check that the size of the given times and values are the same, whatever their type.~
It does not improve the tests, it only fixes the issue: taking into account the fact that the given objects can be ParamObj and not only Variable, and since ParamObj doesn't have the attribute `size`, a user can still provide value and times as Variable of different size, whose build will always fail (but at least the initialization is made possible if their size match).
=> [FIX] Fix definition of InterpolatedWaveform with values as Variable 

release.md
The Pulser documentation is now also hosted at the [docs portal](https://docs.pasqal.cloud/pulser). Upon release the portal needs a manual rebuild and deploy. Instructions for this are now added to `release.md`.
=> Update release instructions

pulser-core/pulser/devices/_device_datacls.py, pulser-core/pulser/exceptions/sequence.py, pulser-core/pulser/json/abstract_repr/schemas/device-schema.json, pulser-core/pulser/register/register.py, tests/test_abstract_repr.py, tests/test_devices.py, tests/test_register.py
=> Add constraints on the minimum layout filling fraction

pulser-core/pulser/backend/config.py, pulser-simulation/pulser_simulation/qutip_backend.py, pulser-simulation/pulser_simulation/qutip_config.py, tests/pulser_simulation/test_qutip_backend_v2.py, tests/test_backend.py
Currently, all the type hints say `Observable` and there is an `isinstance` check too. However, all the code will work with `Callback` too, it's just that the logic about checking evaluation times is not valid anymore for a general `Callback`.
I relaxed the typing a bit. There is currently no validation if the passed object is not an `Observable` since for a general `Callback` you cannot say very much about what it'll do.
=> Allow general callback in EmulationConfig

pulser-core/pulser/sequence/helpers/_switch_device.py, pulser-core/pulser/sequence/sequence.py, tests/test_sequence.py
Quoting @Igoreduardobraga:
> This pull request addresses issue https://github.com/pasqal-io/Pulser/issues/852 by clarifying the error message raised when attempting to configure a non‑existent DMM channel on a device. Previously, the message simply stated:
> 
> 	f"No DMM {dmm_id} in the device."
> 
> And now, the message has been changed to:
> 
> 	f"No DMM called {dmm_id} is available in the device. Your selected device {self._device.name} has the following DMM channels available: {list(self._device.dmm_channels.keys())}."
> 
> Additionally, the related tests have been updated to match the new, detailed error message in the test_sequence file.
> 
> Closes https://github.com/pasqal-io/Pulser/issues/852
Additionnaly, transforms all the sequence._device into sequence.device
=>  FIX: Clarify “No DMM” error message

pulser-core/pulser/backend/abc.py, pulser-core/pulser/sequence/sequence.py, tests/test_backend.py, tests/test_sequence.py
As described in #863, our QPUs don't accept empty sequences. Here I've added a check for this in `Backend.validate_sequence`. I've also added the `is_empty` property to conveniently check if the sequence is empty.
Closes #863
=> Deny empty sequence for mimic_qpu=True

pulser-core/pulser/backend/qpu.py, pulser-core/pulser/backend/remote.py, tests/test_backend.py
Move mimic-qpu validation from PasqalCloud to RemoteBackend
Potential breaking change:
If there are any connections that use mimic-qpu=true but do not implement the `fetch_available_devices` method, this change may cause the run call to fail
=> Move the mimic-QPU validation to RemoteBackend.run()

pulser-core/pulser/parametrized/paramobj.py, pulser-core/pulser/parametrized/variable.py, tests/test_parametrized.py
We have had a long standing issue with binary operations on abstract objects where the order of the arguments influenced the outcomes. 
For example,
```
>>> var = Variable("var", dtype=float, size=2)
>>> arr = np.arange(2)
>>> var + arr   # As expected
<pulser.parametrized.paramobj.ParamObj object at 0x7521dce93df0>
>>> arr + var   # An array of parametrized objects, not what we want
array([<pulser.parametrized.paramobj.ParamObj object at 0x7521dce92e30>,
<pulser.parametrized.paramobj.ParamObj object at 0x7521dce93cd0>],
dtype=object)
```
After some digging, it seems this can be avoided by writing a custom `__array_ufunc__` for the right-hand side object, so that's what we do here.
=> Avoid inconsistent behavior on operations between numpy arrays and parametrized objects

pulser-core/pulser/backend/results.py, pulser-core/pulser/register/base_register.py, tests/test_backend_abstract_repr.py
Even though using non-str qubit IDs is deprecated, it is still allowed and we were not handling it properly when serializing `Results`. This fixes that and also makes the `DeprecationWarning` to not use `int`s as qubit IDs louder.
=> Handle when Results.atom_order entries are not strings

pulser-simulation/pulser_simulation/simulation.py, tests/pulser_simulation/test_qutip_backend_v2.py
There was a sporadic rounding error issue when converting evaluation times to the "legacy evaluation times" expected by `QutipEmulator`.
=> Fix evaluation times rounding error in QutipBackendV2

pulser-core/pulser/register/base_register.py, tests/pulser_simulation/test_simresults.py, tests/pulser_simulation/test_simulation.py, tests/test_devices.py, tests/test_json.py, tests/test_register.py, tests/test_register_layout.py, tests/test_sequence.py, tests/test_sequence_sampler.py, tests/test_waveforms.py
- Reduce the warnings filter from `"always"` to once
- Handle all cases where the warning is raised in the unit tests
=> Deal with deprecation warnings from non-str QubitIDs

pulser-core/pulser/exceptions/sequence.py, pulser-core/pulser/sequence/helpers/_switch_device.py, tests/test_sequence.py
- Fixes issue where the error message was not appearing
- Creates and introduces a custom `SwitchDeviceError`
- Explicitly checks for compatibility of the register with the new device
=> Improve exceptions in Sequence.switch_device()

pulser-core/pulser/_hamiltonian_data/hamiltonian_data.py, pulser-core/pulser/json/abstract_repr/deserializer.py, pulser-core/pulser/noise_model.py, tests/pulser_simulation/test_simulation.py, tests/test_abstract_repr.py, tests/test_hamiltonian_data.py, tests/test_noise_model.py
All other detuning related quantities are in `rad/microsec` so the choice of `Hz` was inconsistent. In addition, in the new units, all quantities in the power spectral density are of order unity, which makes things easier to sanity check.
=> Convert hf detuning noise units from Hz to rad/microsec

pulser-simulation/pulser_simulation/hamiltonian.py, pulser-simulation/pulser_simulation/simulation.py, tests/pulser_simulation/test_hamiltonian.py
You need to instantiate a `Register` or `Register3D` depending on the length of the position vector. `Hamiltonian` always tried `Register`. Fixed the issue by making `Hamiltonian` take a `BaseRegister` rather than a `qdict`.
=> Fix that Hamiltonian does not work with Register3D

.github/workflows/publish.yml, .github/workflows/test.yml
Our CI tests involving drawing with matplotlib fail again, even though we are using the AGG backend, which is still the one advised to solve the issue (see [issue on matplotlib](https://github.com/matplotlib/matplotlib/issues/28957) and [matplotlib doc](https://matplotlib.org/stable/users/explain/figure/backends.html)). 
Trying some stuff to fix it, enable temporarily the CI jobs to run on this PR (to be reverted)
=> Fix CI tkinter
